# -*- coding: utf-8 -*-
"""TimeSeriesFinalExploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DqpKW_251OZbZRNvD3J4epWQHMyYYqU2
"""

!pip install pmdarima

from statsmodels.tsa.arima.model import ARIMA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
from sklearn.ensemble import IsolationForest
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

cyber = pd.read_csv("/content/sample_data/cyber_data.csv")

cyber.head()

# Ensure 'AttackDate' is in the correct datetime format
cyber['AttackDate'] = pd.to_datetime(cyber['AttackDate'], format='%d/%m/%Y %H:%M')

# Now you can plot
plt.figure(figsize=(12, 6))
plt.plot(cyber['AttackDate'], cyber['Spam'], marker="o", linestyle="-", alpha=0.7)
plt.title("Cyber-Attack Trends Over Time (Spam)")
plt.xlabel("Date")
plt.ylabel("Attack Frequency")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(cyber['AttackDate'], cyber['Network Attack'], marker="o", linestyle="-", alpha=0.7)
plt.title("Cyber-Attack Trends Over Time (Network Attack)")
plt.xlabel("Date")
plt.ylabel("Attack Frequency")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# Display basic information
print("Dataset Shape:", cyber.shape)
print("\nMissing Values:\n", cyber.isna().sum())
print("\nBasic Statistics:\n", cyber.describe())


# ACF and PACF plots for trend analysis
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
plot_acf(cyber['Network Attack'].dropna(), ax=axes[0], title="Autocorrelation (ACF)")
plot_pacf(cyber['Network Attack'].dropna(), ax=axes[1], title="Partial Autocorrelation (PACF)")
plt.show()

# Load Data (Assuming cyber is preprocessed)
cyber["Network Attack"] = cyber["Network Attack"].interpolate()  # Fill gapsDrop any remaining NaNs

# Verify there are no NaNs
print(cyber.isna().sum())

# Now run auto_arima
auto_model = auto_arima(cyber["Network Attack"], seasonal=False, trace=True)
best_order = auto_model.order
print(f"Optimal ARIMA Order: {best_order}")

# Auto-Select ARIMA Order
auto_model = auto_arima(cyber["Network Attack"], seasonal=False, trace=True)
best_order = auto_model.order
print(f"Optimal ARIMA Order: {best_order}")

# Fit ARIMA Model
model = ARIMA(cyber["Network Attack"], order=best_order)
model_fit = model.fit()

# Forecast
cyber["Forecast"] = model_fit.predict(start=1, end=len(cyber), dynamic=False)

# Compute Residuals
cyber["Residuals"] = np.abs(cyber["Network Attack"] - cyber["Forecast"])

# **Use Isolation Forest for Anomaly Detection**
iso_forest = IsolationForest(contamination=0.01, random_state=42)
cyber["Anomaly"] = iso_forest.fit_predict(cyber[["Residuals"]])
cyber["Anomaly"] = cyber["Anomaly"] == -1  # Convert to boolean

# Plot Results
plt.figure(figsize=(12,6))
plt.plot(cyber.index, cyber["Network Attack"], label="Actual", color="blue")
plt.plot(cyber.index, cyber["Forecast"], label="ARIMA Forecast", color="green", linestyle="dashed")

# Highlight Anomalies
anomalies = cyber[cyber["Anomaly"]]
plt.scatter(anomalies.index, anomalies["Network Attack"], color="red", label="Anomalies", marker="o")

plt.xlabel("Date")
plt.ylabel("Network Attack Frequency")
plt.title("Anomaly Detection in Cyber-Attacks (ARIMA + Isolation Forest)")
plt.legend()
plt.show()

cyber[cyber['Anomaly'] == False]

cyber[cyber['Anomaly'] == True]

len(cyber[cyber['Anomaly'] == False])/len(cyber)



threshold = cyber["Residuals"].mean() + 3 * cyber["Residuals"].std()
cyber["Anomaly"] = cyber["Residuals"] > threshold

# Plot the time series with forecast and anomalies
plt.figure(figsize=(14,6))
plt.plot(cyber.index, cyber["Network Attack"], label="Actual", color='blue', alpha=0.6)
plt.plot(cyber.index, cyber["Forecast"], label="Forecast", color='red', linestyle="dashed")
plt.scatter(cyber.index[cyber["Anomaly"]], cyber["Network Attack"][cyber["Anomaly"]],
            color='black', marker='o', label="Anomalies")
plt.xlabel("Date")
plt.ylabel("Network Attack Count")
plt.title("Cyber Attack Time Series with Forecast & Anomalies")
plt.legend()
plt.grid()
plt.show()

cyber["Rolling Mean"] = cyber["Network Attack"].rolling(window=7).mean()

plt.figure(figsize=(14,6))
plt.plot(cyber.index, cyber["Rolling Mean"], label="Smoothed Actual (7-day Avg)", color='blue', alpha=0.6)
plt.plot(cyber.index, cyber["Forecast"], label="Forecast", color='red', linestyle="dashed")
plt.scatter(cyber.index[cyber["Anomaly"]], cyber["Network Attack"][cyber["Anomaly"]],
            color='black', marker='o', label="Anomalies")
plt.xlabel("Date")
plt.ylabel("Network Attack Count")
plt.title("Cyber Attack Time Series with Forecast & Anomalies (Smoothed)")
plt.legend()
plt.grid()
plt.show()